Packages
realRoshanRaj/ECE461-P2 pull request #15
Opened 2023-04-13 05:40 UTC by sklee1216

2023-04-13 21:02 UTC, realRoshanRaj commented
Whys the linter failing?

2023-04-13 21:18 UTC, sklee1216 commented
> Whys the linter failing?

I have no idea. we need to update @actions/core but idk how to do.

2023-04-14 19:15 UTC, realRoshanRaj requested changes

2023-04-14 19:15 UTC, realRoshanRaj commented on pkg/db/firebase.go
> +		}
Carat and Tilde have the same logic, no?

2023-04-14 19:15 UTC, realRoshanRaj commented on pkg/utils/utils.go
> +		}
Need to properly parse and store the repository url in the same form

2023-04-16 22:10 UTC, realRoshanRaj approved these changes

2023-04-16 22:11 UTC, merged